### ISSUE TITLE
Roboto: Font request failed with reason code: -1

### ISSUE THREAD

**Issue by zkvarz** [googlesamples/android-DownloadableFonts#2]
Requesting a font. Query: name=Roboto&weight=400&width=100.0&italic=0.0&besteffort=true

**Comment by thagikura** [comment]
Did you install the beta version of Google Play Services? 
https://developers.google.com/android/guides/beta-program

**Comment by zkvarz** [comment]
@thagikura No, I didn't. In the official guideline there is no word about it as I see it:
https://developer.android.com/preview/features/downloadable-fonts.html
Maybe there is a problem, thanks.

**Comment by thagikura** [comment]
It's mentioned in the README in this sample app, not in the documents on developer.android.com since this is a workaround until the v11 version of the Google Play Services (which has the feature for behaving as a font provider) becomes a public version.

**Comment by thagikura** [comment]
Please reopen this if you still see the issue after you install the beta version of Google Play Services.
