### ISSUE TITLE
font request failed with reason code: -1

### ISSUE THREAD

**Issue by niravtopsy** [googlesamples/android-DownloadableFonts#3]
Hello

I download this example and run it on nexus 6P. I request for font but it giving me the error message.

This giving error like following, so i can't able to check how to downloadable fonts can be download and set to out text. so please suggest me to how to solve this or anything missing on it ?

Error message while requesting font :+1: 

Font Family Name : ABeeZee

Error message : Font request failed with reason code: -1

**Comment by thagikura** [comment]
Could you make sure your device has Google Play Services with v11+ installed (like version 11.8.12) ?

The sample app requires Google Play Services v11+ to work properly.
