### ISSUE TITLE
Andorid O font not working

### ISSUE THREAD

**Issue by gomeskingsley** [googlesamples/android-DownloadableFonts#5]
I have the following gradle configuration

```
compileSdkVersion 26
buildToolsVersion "26.0.1" 

minSdkVersion 21
targetSdkVersion 21

compile 'com.android.support:support-compat:26.0.1
def android_arch_version = '1.0.0-alpha8'
compile "android.arch.lifecycle:runtime:$android_arch_version"
compile "android.arch.lifecycle:extensions:$android_arch_version"
annotationProcessor "android.arch.lifecycle:compiler:$android_arch_version"
```

In xml :
`<...android:fontFamily="@font/sans_light"/>
`

The font works if my activity extends AppCompatActivity
The font does not work if the Activity extends LifecycleActivity

Attached 2 screen shots : [ibb.co/cT4J9v]([ibb.co/cT4J9v) - extending AppCompat (works fine) [ibb.co/kJzkpv](ibb.co/kJzkpv)- extending LifecycleActivity (does not work)

**Comment by sanjitsulaiman** [comment]
Myanmar zawgiy fond

**Comment by gomeskingsley** [comment]
This bug was fixed in the latest support library
